name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential file
      
    - name: Build mkbom
      run: make all
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: mkbom
        # A file, directory or wildcard pattern that describes what to upload
        path: build/bin/mkbom
        # The desired behavior if no files are found using the provided path.

      
   
